### ISSUE TITLE
LoRas are not always file-integrity checked 

### ISSUE THREAD

**Issue by tazlin** [Haidra-Org/hordelib#146]
LoRa files can be fetched/validated by the LoRa MM and then sent to comfyui, at which point when they are attempted to be read from off disk, the `.safetensors` file turns out to be an HTML webpage.

- Is the SHA hash considered/fetched from civitai?
- Are we integrity-checking files in all cases?
- Is there a way to fail more gracefully in the off chance the file turns out to be corrupt on disk anyway? (such as an invalid file being uploaded to civitai).

**Comment by db0** [comment]
The only way I can imagine is an invalid file on civitai yes. The file is not saved unless the hash checks out iirc.
