### ISSUE TITLE
Post Processing clears image faults (gen_metadata)

### ISSUE THREAD

**Issue by aiscribbles** [Haidra-Org/hordelib#263]
https://github.com/Haidra-Org/hordelib/blob/d0158dba464b87d26628565bab7959b8330f2bdb/hordelib/horde.py#L1367

This line sets the single_image_faults to an empty list. And then later that is returned as the overall list of faults for that result. But the original list of faults (stored in the variable `faults`) needs to be merged with that. 

I would recommend replacing the referenced line with the following, or something to this effect. Copying the previous faults list as a starting point for the single_image_faults variable. 

single_image_faults = faults[:]

**Comment by aiscribbles** [comment]
there's a chance i'm misunderstanding something in this bit of code. But some local testing on my part confirms that when I use post-processors, the /status/ endpoint never returns the expected gen_metadata.

**Comment by aiscribbles** [comment]
Just made a pull request with this change: #295

**Comment by tazlin** [comment]
Closed via https://github.com/Haidra-Org/hordelib/pull/298. Thanks again
