### ISSUE TITLE
Fully support n_iter ('batch size')

### ISSUE THREAD

**Issue by tazlin** [Haidra-Org/hordelib#83]
- A good deal of ground work is laid, and can be seen in `comfy_horde.py` and `horde.py`, but thorough testing would be required, and support from the API, to be sure it is in a production ready state.

**Comment by db0** [comment]
Do we already have unit tests for it?

**Comment by tazlin** [comment]
Hordelib roughly supports it; it was written (by jug) from the beginning with support for it. I actually specifically refactored `HordeLib` (the class) and all of the tests to use `basic_inference_single_image(...)` specifically to highlight this fact. `basic_inference(...)` now always returns a list of images, and any payload from the horde (or mocked in the tests) with `n_iter` will return as many images as specified through the batching mechanism.

(and just to answer your question, no test uses `n_iter` > 1, but it is trivial to confirm it works.)

reGen also presumes that any results from hordelib may contain multiple images, and the only short coming (that I am aware of) in that worker is that it wouldn't be able to POST more than one image.

**Comment by tazlin** [comment]
> Do we already have unit tests for it?

You could modify the test in `test_horde_inference.py` accordingly to see the behavior: (I will work on proper unit testing when this becomes the active focus of my efforts):

```python
class TestHordeInference:
    def test_text_to_image(
        self,
        hordelib_instance: HordeLib,
        stable_diffusion_model_name_for_testing: str,
    ):
        data = {
            "sampler_name": "k_dpmpp_2m",
            "cfg_scale": 7.5,
            "denoising_strength": 1.0,
            "seed": 123456789,
            "height": 512.1,  # test param fix
            "width": 512.1,  # test param fix
            "karras": False,
            "tiling": False,
            "hires_fix": False,
            "clip_skip": 1,
            "control_type": None,
            "image_is_control": False,
            "return_control_map": False,
            "prompt": "an ancient llamia monster",
            "ddim_steps": 25,
            "n_iter": 2,
            "model": stable_diffusion_model_name_for_testing,
        }
        pil_images = hordelib_instance.basic_inference(data)

        for i, pil_image in enumerate(pil_images):
            assert pil_image is not None
            assert isinstance(pil_image, Image.Image)

            img_filename = f"text_to_image_{i}.png"
            pil_image.save(f"images/{img_filename}", quality=100)
            
```

**Comment by tazlin** [comment]
https://github.com/Haidra-Org/hordelib/pull/158

**Comment by tazlin** [comment]
Closed by https://github.com/Haidra-Org/hordelib/pull/158
